#!/usr/bin/env python3

import sys, argparse
import jenerator


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='A static site generator')
    subparsers = parser.add_subparsers(description='Valid subcommands')
    # Build command
    parser_build = subparsers.add_parser('build', aliases=['b'],
            help='Build a site')
    parser_build.add_argument('--source', '-s', type=str, default='.',
            help='Path to site source files')
    parser_build.add_argument('--target', '-t', type=str, default='_build',
            help='Directory to store output files')
    parser_build.add_argument('--overwrite', action='store_true', default=False,
            help='Delete the build target directory before building')
    parser_build.set_defaults(func=jenerator.cmd_build)

    opts = parser.parse_args(sys.argv[1:])
    opts.func(opts)
