#!/usr/bin/env python3

import sys, argparse
import jenerator


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='A static site generator')
    subparsers = parser.add_subparsers(description='Valid subcommands')
    # Init command
    parser_init = subparsers.add_parser('init', aliases=['i'],
            help='Initialize a new site directory structure (optional)')
    parser_init.add_argument('--location', '-l', type=str, default='.',
            help='Path to site root directory')
    parser_init.add_argument('--title', type=str, default='',
            help='Site title')
    parser_init.add_argument('--author', type=str, default='',
            help='Site author name')
    parser_init.add_argument('--email', type=str, default='',
            help='Author email address')
    parser_init.add_argument('--url', type=str, default='',
            help='Site deploy URL')
    parser_init.set_defaults(func=jenerator.cmd_init)
    # Config command
    parser_config = subparsers.add_parser('config', aliases=['c'],
            help='Configure site options')
    parser_config.add_argument('--site', type=str, default='.',
            help='Path to directory of site to configure')
    parser_config.add_argument('--set', type=str, default='',
            help='Set an option, <option>=<value>')
    parser_config.add_argument('--option', type=str, default='',
            help='Option to display')
    parser_config.set_defaults(func=jenerator.cmd_config)
    # Build command
    parser_build = subparsers.add_parser('build', aliases=['b'],
            help='Build a site')
    parser_build.add_argument('--site', '-s', type=str, default='.',
            help='Path to site source files')
    parser_build.add_argument('--target', '-t', type=str, default='_build',
            help='Directory to store output files')
    parser_build.add_argument('--overwrite', action='store_true', default=False,
            help='Delete the build target directory before building')
    parser_build.add_argument('--nostatic', action='store_true', default=False,
            help='Do not require a static files directory')
    parser_build.add_argument('--feeds', action='store_true', default=False,
            help='Build RSS and Atom feeds for categories and the index')
    parser_build.set_defaults(func=jenerator.cmd_build)

    opts = parser.parse_args(sys.argv[1:])
    opts.func(opts)
